from .mcp_config import MCP_SERVER_NAME, MCP_SERVER_URL, MCP_TOOLS


TOOL_DEFINITIONS = [
    {
        "name": "review_equity_order",
        "mcp_server": MCP_SERVER_NAME,
        "mcp_url": MCP_SERVER_URL,
        "mcp_tool": MCP_TOOLS["review_equity_order"],
        "description": "Review an equity order before placement. Does not place a real trade.",
        "requires_authorization": ["robinhood.read", "robinhood.trade_review"],
        "input_schema": {
            "type": "object",
            "required": ["account_id", "symbol", "side", "order_type", "time_in_force"],
            "properties": {
                "account_id": {"type": "string"},
                "symbol": {"type": "string"},
                "side": {"enum": ["buy", "sell"]},
                "order_type": {"enum": ["market", "limit", "stop", "stop_limit"]},
                "time_in_force": {"enum": ["gfd", "gtc", "ioc", "opg"]},
                "quantity": {"type": "string", "description": "Decimal quantity as a string."},
                "notional": {"type": "string", "description": "Dollar notional as a decimal string."},
                "limit_price": {"type": "string"},
                "stop_price": {"type": "string"},
                "extended_hours": {"type": "boolean", "default": False},
            },
        },
    },
    {
        "name": "place_equity_order",
        "aliases": ["place_stock_order"],
        "mcp_server": MCP_SERVER_NAME,
        "mcp_url": MCP_SERVER_URL,
        "mcp_tool": MCP_TOOLS["place_equity_order"],
        "description": "Place a real equity order after review and explicit user confirmation.",
        "requires_authorization": ["robinhood.read", "robinhood.trade_review", "robinhood.trade_write"],
        "safety": [
            "account.agentic_allowed must be true",
            "review_id and matching approval_id are always required",
            "approval must be persisted, unexpired, approved in Codex, and match unchanged order parameters",
            "confirmed must be true after the user approves the final order",
            "account_id is required when multiple accounts exist",
        ],
        "input_schema": {
            "type": "object",
            "required": ["account_id", "symbol", "side", "order_type", "time_in_force", "review_id", "approval_id", "confirmed"],
            "properties": {
                "account_id": {"type": "string"},
                "symbol": {"type": "string"},
                "side": {"enum": ["buy", "sell"]},
                "order_type": {"enum": ["market", "limit", "stop", "stop_limit"]},
                "time_in_force": {"enum": ["gfd", "gtc", "ioc", "opg"]},
                "quantity": {"type": "string"},
                "notional": {"type": "string"},
                "limit_price": {"type": "string"},
                "stop_price": {"type": "string"},
                "extended_hours": {"type": "boolean", "default": False},
                "review_id": {"type": "string"},
                "approval_id": {"type": "string"},
                "confirmed": {"type": "boolean"},
            },
        },
    },
    {
        "name": "cancel_equity_order",
        "aliases": ["cancel_stock_order"],
        "mcp_server": MCP_SERVER_NAME,
        "mcp_url": MCP_SERVER_URL,
        "mcp_tool": MCP_TOOLS["cancel_equity_order"],
        "description": "Cancel a real equity order after explicit user confirmation.",
        "requires_authorization": ["robinhood.read", "robinhood.trade_write"],
        "safety": [
            "account.agentic_allowed must be true",
            "confirmed must be true after the user approves the cancellation",
            "order must belong to the requested account",
            "filled, cancelled, and rejected orders cannot be cancelled",
        ],
        "input_schema": {
            "type": "object",
            "required": ["account_id", "order_id", "confirmed"],
            "properties": {
                "account_id": {"type": "string"},
                "order_id": {"type": "string"},
                "confirmed": {"type": "boolean"},
            },
        },
    },
    {
        "name": "review_option_order",
        "mcp_server": MCP_SERVER_NAME,
        "mcp_url": MCP_SERVER_URL,
        "mcp_tool": MCP_TOOLS["review_option_order"],
        "description": "Review an option order before placement. Does not place a real trade.",
        "requires_authorization": ["robinhood.read", "robinhood.option_review"],
        "safety": [
            "account.agentic_allowed must be true",
            "limit_price is required",
            "only review is implemented; option placement is intentionally not included",
        ],
        "input_schema": {
            "type": "object",
            "required": ["account_id", "legs", "order_type", "time_in_force", "limit_price"],
            "properties": {
                "account_id": {"type": "string"},
                "legs": {"type": "array", "minItems": 1},
                "order_type": {"const": "limit"},
                "time_in_force": {"enum": ["gfd", "gtc", "ioc", "opg"]},
                "limit_price": {"type": "string"},
                "direction": {"enum": ["debit", "credit", "even"]},
            },
        },
    },
]
